site_name: Tulip
repo_url: https://gitlab.com/drid/tulip
nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - OpenRally: openrally.md
  - Shortcuts: shortcuts.md
theme:
  name: material
  palette:
    primary: amber

extra:
  analytics:
    provider: google
    property: G-1VYMMX1XZ4